build:
	docker build . -t bmuchacho/network-debugger:1.2 --platform linux/x86_64
	docker push bmuchacho/network-debugger:1.2

run:
	docker run -it --platform linux/x86_64 bmuchacho/network-debugger:1.2

