apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minio-creds # access key (3 - 20 chars) / secret key (4 - 40 chars)
  namespace: minio
stringData:
  ACCESS_KEY: DF38434DA6B85DE5 
  SECRET_KEY: 78651188E91E2EE4FD5A5D85A74AC
